Added HW1 and HW2
NickGeorgiev/oop-kn-2020-group4-shared pull request #28
Opened 2020-04-04 18:42 UTC by tsankoangelov

@NickGeorgiev  Review

2020-04-22 19:42 UTC, tsankoangelov commented
RCS 3

2020-04-24 16:09 UTC, NickGeorgiev requested changes
Оправи си идентацията в cpp файла

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.h
> +    char back();
Трябва да могат да работят с константни обекти също

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.h
> +    bool empty();
const?

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.h
> +    size_t getCapacity();
const? а и да не говорим, че имената не отговарят на условието

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.h
> +    operator bool();
искаме само експлицитно конвертиране
const??

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.h
> +    char operator[](size_t);
трябва да може да работи с константни обекти

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
Няма смисъл здаделената памет да бъде различна от капацитета.

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
бих сложил по-голям капацитет

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
new_char_array няма памет
изгубвам се в този метод - преоразмеряването да се изнесе в отделна функция и става на 3 реда, даже 2

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
данните стават неконсистентни.
Увеличаваме капацитета, без да заделим толкова памет
Променяме размера, без да сме променили реалния низ.

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
добре е да се assert-ва ако индекса не е коректен или да се хвърли изключение

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
пак не заделяш памет

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
нека да заделяш памет с точния размер, а не с капацитета

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +    }
това съм го чел на друго място

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +      }
ако няма място? а и трбява да върнеш текущия обект

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +      }
пак проблема с паметта

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS1/String.cpp
> +      }
на един ред моля

2020-04-24 16:09 UTC, NickGeorgiev commented on student_work/TsankoAngelov/RCS3/LList.cpp
> +}
тези еднобуквени променливи, развътяни на няколко пъти са твърде объркващи, изглежда ми окей без последния ред

2024-10-16 15:12 UTC, closed without merging